CREATE TABLE `posts` (
     `id`	BIGINT UNSIGNED	NOT NULL PRIMARY KEY AUTO_INCREMENT, 
     `user_id`	BIGINT UNSIGNED	NOT NULL,  
     `content`	VARCHAR(2000)	NOT NULL,
     `image`	VARCHAR(100)	NOT NULL,
     `created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP(),
     `updated_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP(),
     `deleted_at`	DATETIME	NULL	DEFAULT NULL
);
